// Grammatik-Nachschlagewerk für den Lese-Trainer.
// Beim Antippen einer Sinneinheit wird ihr Text nach diesen Mustern durchsucht.
//   t: 'g' = als Teilzeichenkette suchen (längste zuerst).
//   t: 'p' = nur als ABSCHLUSS-Partikel der Einheit; nk:true = nur wenn Kanji in der Einheit.
// Erklärungen im Minna-/Chuukyuu-Stil: direkt, einfach, mit Beispiel.
window.LESEN_GRAMMAR = [
  // --- Fall-/Themapartikel (am Ende der Sinneinheit) ---
  { k:"は", t:"p", nk:true,  label:"は (Themapartikel)", de:"Das kleine は hängst du hinter das Thema des Satzes — »was X angeht …«. Achtung: hier sprichst du es »wa«. (Minna L1)" },
  { k:"が", t:"p", nk:true,  label:"が (Subjekt)", de:"Zeigt, WER etwas tut, oder hebt eine neue/wichtige Info hervor. Steht auch bei 好き, できる und ある. (L4/L8)" },
  { k:"を", t:"p", nk:true,  label:"を (Objekt)", de:"Hängst du hinter das, womit etwas gemacht wird (das Objekt). Gesprochen »o«. Bei Bewegung auch die Strecke: 橋を渡る. (L6/L23)" },
  { k:"に", t:"p", nk:true,  label:"に (Ziel/Zeit/Ort)", de:"Der Allrounder: Ziel, Empfänger, fester Zeitpunkt (7時に) und der Ort, WO etwas ist (に いる/ある). (L4/L7/L10)" },
  { k:"へ", t:"p", nk:true,  label:"へ (Richtung)", de:"Zeigt die Richtung »nach/zu«. Wird »e« gesprochen. (L5)" },
  { k:"と", t:"p", nk:true,  label:"と (und/mit/Zitat)", de:"Drei Jobs: »und« zwischen Nomen, »mit« (Person) und der Zitat-Marker (…と言う »sagen, dass …«). (L4/L5/L21)" },
  { k:"も", t:"p", nk:true,  label:"も (auch)", de:"»auch« — es ersetzt は/が/を. Mit Verneinung wird daraus »nicht einmal«. (L1)" },
  { k:"の", t:"p", nk:true,  label:"の (Genitiv/Verbindung)", de:"Verbindet zwei Nomen: 私の本 »mein Buch«. Macht auch aus einem ganzen Satz ein Nomen. (L1/L38)" },
  { k:"や", t:"p", nk:true,  label:"や (und u.a.)", de:"Wie »und«, aber für eine unvollständige Liste: »… und so weiter«." },
  { k:"か", t:"p", nk:false, label:"か (Frage)", de:"Häng es ans Satzende — fertig ist die Frage. (L1)" },
  { k:"ね", t:"p", nk:false, label:"ね (nicht wahr?)", de:"Du suchst Zustimmung: »…, oder?«, »…, nicht wahr?«." },
  { k:"よ", t:"p", nk:false, label:"よ (Betonung)", de:"Du betonst deine Info für den Hörer: »ich sag dir …«, »echt jetzt«." },
  // --- mehrzeichige Partikel/Verbindungen ---
  { k:"から", t:"g", label:"から (von/ab/weil)", de:"Zwei Bedeutungen: »von/ab« (Zeit/Ort) — oder »weil« hinter einem Grund. (L4/L9)" },
  { k:"まで", t:"g", label:"まで (bis)", de:"»bis« (Zeit, Ort, Zustand). までに heißt »bis spätestens«. (L4)" },
  { k:"より", t:"g", label:"より (als)", de:"Der Vergleich »als«. Das Adjektiv dahinter bleibt unverändert. (L12)" },
  { k:"など", t:"g", label:"など (usw.)", de:"»und so weiter« — du nennst ein paar Beispiele, die Liste ist nicht komplett." },
  { k:"だけ", t:"g", label:"だけ (nur)", de:"»nur«, ganz neutral. (L11)" },
  { k:"しか", t:"g", label:"しか …ない (nur)", de:"Auch »nur«, aber zusammen mit Verneinung und dem Beiklang »leider nur so wenig«. (L27)" },
  { k:"ばかり", t:"g", label:"ばかり (nur/gerade erst)", de:"»nur/ständig« — oder nach der た-Form »gerade erst«: 来たばかり. (L46)" },
  // --- Erklärungs-/Stilendungen ---
  { k:"んです", t:"g", label:"んです (Erklärung)", de:"Du erklärst Grund oder Hintergrund: »es ist nämlich so, dass …«. (L26)" },
  { k:"るんだ", t:"g", label:"〜んだ (Erklärung, plain)", de:"Die lockere (Plain-)Form von んです: »es ist nämlich so, dass …«. (L20/L26)" },
  { k:"たんだ", t:"g", label:"〜んだ (Erklärung, plain)", de:"Die lockere (Plain-)Form von んです nach der た-Form: »…, nämlich«. (L20/L26)" },
  { k:"でしょう", t:"g", label:"でしょう (Vermutung/oder?)", de:"»…wird wohl« (Vermutung) — oder mit Frageton »…, oder?«. (L32)" },
  { k:"だろう", t:"g", label:"だろう (Vermutung, plain)", de:"Die lockere Form von でしょう: »wohl«." },
  // --- て-Form-Anschlüsse ---
  { k:"ています", t:"g", label:"〜ている (Verlauf/Zustand)", de:"Etwas läuft gerade (»ist gerade dabei«) — oder ein Zustand hält an. (L14/L15)" },
  { k:"ている", t:"g", label:"〜ている (Verlauf/Zustand)", de:"Dasselbe in der Plain-Form: »gerade dabei« / Dauerzustand. (L14/L15)" },
  { k:"でいます", t:"g", label:"〜ている (Verlauf/Zustand)", de:"Wie ている, nur mit で-Laut nach ん/む/ぶ/ぐ (z. B. 読んでいます). (L14/L15)" },
  { k:"でいる", t:"g", label:"〜ている (Verlauf/Zustand)", de:"Plain-Form mit で-Laut: 飲んでいる »trinkt gerade«. (L14/L15)" },
  { k:"ていまし", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"Vergangenheit: »war gerade dabei / war im Zustand …«." },
  { k:"ていた", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"Die Plain-Vergangenheit von ている." },
  { k:"でいまし", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"»war gerade dabei …«, mit で-Laut (nach ん/む/ぶ/ぐ)." },
  { k:"でいた", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"Plain-Vergangenheit mit で-Laut." },
  { k:"てある", t:"g", label:"〜てある (vorbereitet)", de:"Jemand hat etwas absichtlich getan, und es ist jetzt in dem Zustand (z. B. vorbereitet). (L30)" },
  { k:"ておく", t:"g", label:"〜ておく (im Voraus)", de:"Etwas schon im Voraus erledigen, vorbereiten. (L30)" },
  { k:"てしまい", t:"g", label:"〜てしまう (leider/ganz)", de:"Zwei Gefühle: »leider/aus Versehen« (Bedauern) oder »ganz fertig« (Vollendung). (L29)" },
  { k:"てしまう", t:"g", label:"〜てしまう (leider/ganz)", de:"Zwei Gefühle: »leider/aus Versehen« (Bedauern) oder »ganz fertig« (Vollendung). (L29)" },
  { k:"てしま", t:"g", label:"〜てしまう (leider/ganz)", de:"»leider/aus Versehen« oder »ganz fertig« — auch てしまった/てしまって. (L29)" },
  { k:"でしま", t:"g", label:"〜てしまう (leider/ganz)", de:"Dasselbe mit で-Laut: 飲んでしまった »hab's leider ganz ausgetrunken«. (L29)" },
  { k:"ちゃっ", t:"g", label:"〜ちゃう (=てしまう, ugs.)", de:"Lockere Verschmelzung von てしまう: 飲んじゃった »hab's leider ausgetrunken«." },
  { k:"じゃっ", t:"g", label:"〜じゃう (=でしまう, ugs.)", de:"Lockere Form von でしまう: 死んじゃった." },
  { k:"てくれ", t:"g", label:"〜てくれる (für mich)", de:"Jemand tut etwas für MICH — als Gefallen. (L24)" },
  { k:"てもらえ", t:"g", label:"〜てもらえる (bekommen können)", de:"»ich kann mir … tun lassen / bekomme … getan«. (L24)" },
  { k:"てもらお", t:"g", label:"〜てもらおう (ich lasse …)", de:"»ich werde mir … tun lassen« (Willensform von てもらう). (L24)" },
  { k:"てもらう", t:"g", label:"〜てもらう (sich tun lassen)", de:"Ich lasse jemanden etwas für mich tun und profitiere davon. (L24)" },
  { k:"てあげ", t:"g", label:"〜てあげる (für andere)", de:"Ich tue jemandem (einem anderen) einen Gefallen. (L24)" },
  { k:"ていただ", t:"g", label:"〜ていただく (höflich für mich)", de:"Die höfliche Variante: ein Höhergestellter tut etwas für mich. (L41)" },
  { k:"てください", t:"g", label:"〜てください (bitte tu)", de:"Die höfliche Bitte: »bitte tu …«. (L14)" },
  { k:"てくる", t:"g", label:"〜てくる (her/allmählich)", de:"Bewegung auf mich ZU — oder eine Entwicklung bis jetzt. (L43)" },
  { k:"ていく", t:"g", label:"〜ていく (weg/künftig)", de:"Bewegung von mir WEG — oder eine Entwicklung in die Zukunft. (L43)" },
  { k:"てもいい", t:"g", label:"〜てもいい (darf)", de:"»du darfst …«. Mit か fragst du um Erlaubnis. (L15)" },
  { k:"てはいけ", t:"g", label:"〜てはいけない (darf nicht)", de:"Das Verbot: »du darfst nicht …«. (L15)" },
  // --- ない-Form-Anschlüsse ---
  { k:"ないで", t:"g", label:"〜ないで (ohne/bitte nicht)", de:"»ohne zu …« — oder als Bitte ないでください »bitte nicht …«. (L17/L34)" },
  { k:"なければ", t:"g", label:"〜なければ (muss/wenn nicht)", de:"なければならない heißt »muss«; allein auch »wenn nicht …«. (L17)" },
  { k:"なくても", t:"g", label:"〜なくてもいい (muss nicht)", de:"なくてもいい »du musst nicht / auch ohne … ist's okay«. (L17)" },
  { k:"なくなる", t:"g", label:"〜なくなる (nicht mehr)", de:"»wird nicht mehr …« — eine Veränderung weg von etwas." },
  { k:"なくなり", t:"g", label:"〜なくなる (nicht mehr)", de:"»wird/wurde nicht mehr …«." },
  // --- Modalität / Vermutung ---
  { k:"かもしれ", t:"g", label:"かもしれない (vielleicht)", de:"»vielleicht / könnte sein«. (L32)" },
  { k:"はず", t:"g", label:"はず (müsste)", de:"Eine begründete Erwartung: »das müsste so sein«. Verneint はずがない »kann gar nicht sein«. (L46)" },
  { k:"そう", t:"g", label:"そう (sieht aus / man sagt / so)", de:"Nach Verb-ますStamm/Adjektiv: »sieht … aus« (止まりそう); nach Plain-Form: »man sagt, dass …«. Allein そう = »so, genau«. (L40/L43/L47)" },
  { k:"ようだ", t:"g", label:"ようだ (scheint)", de:"Deine eigene Vermutung: »es scheint, als ob …«. (L47)" },
  { k:"ように", t:"g", label:"ように (wie/damit)", de:"»wie« (Vergleich) oder »damit« (Ziel) — der Kontext entscheidet. (L36)" },
  { k:"ような", t:"g", label:"ような (wie ein …)", de:"»wie ein …«, direkt vor einem Nomen. (L47)" },
  { k:"かのよう", t:"g", label:"〜かのようだ (als ob)", de:"»(gerade) so, als ob …« — oft mit まるで. Vergleich mit etwas Irrealem. (N3)" },
  { k:"のように", t:"g", label:"のように (wie)", de:"Vergleich: »(genau) wie …«." },
  { k:"みたい", t:"g", label:"みたい (wie/scheint)", de:"Die lockere Form von ようだ: »wie/scheint«." },
  { k:"らしい", t:"g", label:"らしい (anscheinend)", de:"Vermutung aus (oft fremden) Infos: »anscheinend, wie man hört«." },
  // --- Konditionale / Verbindungen ---
  { k:"たら", t:"g", label:"〜たら (wenn/falls)", de:"Das flexibelste »wenn/falls/nachdem«. (L25)" },
  { k:"なら", t:"g", nf:"ない", label:"なら (was … betrifft)", de:"»wenn es um … geht« — du greifst ein Thema auf. (L35)" },
  { k:"ても", t:"g", na:"と", label:"〜ても (auch wenn)", de:"»auch wenn / selbst wenn …«. (L25)" },
  { k:"でも", t:"g", label:"でも (aber / auch / auch wenn)", de:"Drei Fälle: am Satzanfang »aber«; nach Nomen/な-Adj »auch/sogar«; nach て-Form »auch wenn«. (L21/L25)" },
  { k:"のに", t:"g", na:"も", label:"のに (obwohl)", de:"»obwohl« — mit einem Beiklang von Enttäuschung oder Ärger. (L45)" },
  { k:"ので", t:"g", label:"ので (weil)", de:"Ein weicher, höflicher Grund: »da/weil«. (L39)" },
  { k:"けど", t:"g", label:"けど (aber)", de:"Lockeres »aber/zwar«. (L20)" },
  { k:"けれど", t:"g", label:"けれど (aber)", de:"Etwas höflicheres »aber/jedoch«." },
  // --- Verbformen / Hilfskonstruktionen ---
  { k:"なければなり", t:"g", label:"なければならない (muss)", de:"Die Pflicht: »ich muss …«. (L17)" },
  { k:"ことができ", t:"g", label:"ことができる (können)", de:"»können« — Fähigkeit oder Möglichkeit. (L18)" },
  { k:"ことがある", t:"g", label:"〜たことがある (Erfahrung)", de:"»schon einmal getan haben« — eine Erfahrung. (L19)" },
  { k:"ことがあ", t:"g", label:"〜たことがある (Erfahrung)", de:"»schon einmal getan haben« — eine Erfahrung (auch ことがあります/あった). (L19)" },
  { k:"つもり", t:"g", label:"つもり (Absicht)", de:"Deine feste Absicht: »ich habe vor zu …«. (L31)" },
  { k:"ながら", t:"g", label:"〜ながら (während)", de:"Zwei Dinge gleichzeitig, von derselben Person: »während ich …«. (L28)" },
  { k:"たり", t:"g", label:"〜たり〜たり (mal … mal)", de:"〜たり〜たり zählt Beispiel-Handlungen auf: »mal dies, mal das«. (L19)" },
  { k:"ようとし", t:"g", label:"〜ようとする (versuchen)", de:"»versuchen zu … / gerade ansetzen zu …«." },
  { k:"ようと", t:"g", label:"〜ようと思う (Vorhaben)", de:"Willensform + と思う = »ich will/habe vor zu …«. (L31)" },
  { k:"させられ", t:"g", label:"使役受身 (gezwungen werden)", de:"Kausativ + Passiv: »ich werde gezwungen, … zu tun« — gegen meinen Willen. (Chuukyuu)" },
  { k:"させて", t:"g", label:"使役 (lassen/zwingen) + て", de:"Kausativ-て: »lassen/zwingen«; mit ください bittest du um Erlaubnis. (L48)" },
  { k:"させる", t:"g", label:"使役 (lassen/zwingen)", de:"Der Kausativ: jemanden etwas tun lassen oder dazu zwingen. (L48)" },
  { k:"られ", t:"g", label:"られる (Passiv/Potential/Respekt)", de:"Drei Möglichkeiten je nach Kontext: Passiv »wird …«, Potential »kann …« oder höflicher Respekt. (L27/L37/L49)" },
  { k:"ところ", t:"g", label:"ところ (Moment/gerade; Ort)", de:"Die Phase einer Handlung: gerade dabei — oder eben fertig (するところ/したところ). Als Nomen auch »Ort, Stelle«. (L46)" },
  { k:"すぎ", t:"g", label:"〜すぎる (zu sehr)", de:"»zu sehr / übermäßig …«. (L44)" },
  { k:"やすい", t:"g", label:"〜やすい (leicht zu)", de:"»leicht zu …« (z. B. leicht zu lesen). (L44)" },
  { k:"にくい", t:"g", label:"〜にくい (schwer zu)", de:"»schwer zu …«. (L44)" },
  { k:"ほど", t:"g", label:"ほど (so sehr/je…desto)", de:"»so sehr, dass …« — oder ば〜ほど »je … desto …«. (L35)" },
  { k:"ずに", t:"g", label:"〜ずに (ohne zu)", de:"Schriftsprachlich für ないで: »ohne zu …«. する wird zu せずに. (Chuukyuu)" },
  { k:"たい", t:"g", label:"〜たい (möchte)", de:"Dein Wunsch: »ich möchte … tun«. (L13)" },
  // --- N3-Spotlights (eine neue Regel pro Lese-Kapitel) ---
  { k:"ようになる", t:"g", label:"〜ようになる (allmähliche Veränderung)", de:"Hängst du an ein Verb (oft die Kann-Form) und zeigst eine Veränderung über die Zeit: früher nicht, jetzt schon. 話せるようになる »sprechen lernen«. Gegenteil: 〜なくなる. (N3)" },
  { k:"ようにな", t:"g", label:"〜ようになる (allmähliche Veränderung)", de:"Veränderung über die Zeit: »es kommt dazu, dass …« (auch ようになった/なりました). (N3)" },
  { k:"たびに", t:"g", label:"〜たびに (jedes Mal wenn)", de:"Nの／Vる + たびに = »jedes Mal, wenn …« — ganz regelmäßig, ohne Ausnahme. (N3)" },
  { k:"ために", t:"g", label:"〜ために (um zu / wegen)", de:"Vる／Nの + ために = »um zu …« (Ziel). Mit Vergangenheit/Unkontrollierbarem heißt es »wegen«. (N3/L42)" },
  { k:"ための", t:"g", label:"〜ための (für / um zu)", de:"Dasselbe ために, aber direkt vor einem Nomen: »ein … zum/für …«. (N3/L42)" },
  { k:"まま", t:"g", label:"〜まま (unveränderter Zustand)", de:"た-Form/Nの/Adj + まま = »so wie es ist, belassen«. 電気をつけたまま »mit angelassenem Licht«. (N3)" },
  { k:"について", t:"g", label:"〜について (über / bezüglich)", de:"N + について = »über … / was … betrifft«. Vor einem Nomen: についての. (N3)" },
  { k:"さえ", t:"g", label:"〜さえ／さえ…ば (sogar / wenn nur)", de:"さえ betont »sogar / nicht einmal«. Und さえ…ば heißt »wenn nur … (dann reicht's)«. (N3)" },
  { k:"わけがない", t:"g", label:"〜わけがない (kann unmöglich sein)", de:"»dafür gibt es keinen Grund« → »das kann unmöglich so sein«. (N3)" },
  { k:"わけが", t:"g", label:"〜わけがない (kann unmöglich sein)", de:"»dafür gibt es keinen Grund« → »das kann unmöglich so sein«. (N3)" },
  { k:"わけで", t:"g", label:"〜わけだ／わけではない (logischer Schluss)", de:"わけだ »das heißt also / logisch«; わけではない »das heißt nicht unbedingt«. (N3)" },
  { k:"きれない", t:"g", label:"〜きれない (nicht ganz …-können)", de:"Vます+きる »ganz zu Ende tun«; verneint きれない »(es ist zu viel) nicht schaffen«. 数えきれない »unzählig«. (N3)" },
  { k:"きれて", t:"g", label:"〜きれない (nicht ganz …-können)", de:"Vます+きる »ganz zu Ende tun«; verneint きれない/きれて »(zu viel) nicht ganz schaffen«. (N3)" },
  { k:"きれた", t:"g", label:"〜きれない (nicht ganz …-können)", de:"Vます+きる »ganz zu Ende tun«; 〜きれた/きれない. (N3)" },
  { k:"きれず", t:"g", label:"〜きれない (nicht ganz …-können)", de:"Vます+きれず = »nicht ganz schaffen, und …«. (N3)" },
  { k:"ところだった", t:"g", label:"〜ところだった (beinahe wäre …)", de:"»um ein Haar wäre … passiert (ist aber nicht)« — oft mit もう少しで. (N3)" },
  { k:"ところでした", t:"g", label:"〜ところだった (beinahe wäre …)", de:"Höfliche Form von 〜ところだった: »um ein Haar wäre … passiert (ist aber nicht)« — oft mit もう少しで. (N3)" },
  { k:"ないと", t:"g", label:"〜ないと(いけない) (muss / sonst)", de:"»wenn nicht …(, dann schlecht)« → kurz für »ich muss …«. Der zweite Teil bleibt oft weg. (N3)" },
  { k:"とたん", t:"g", label:"〜たとたん（に）(kaum dass / im selben Moment)", de:"た-Form + とたん = »kaum dass … / im selben Moment, als …« — meist mit Überraschung. (N3)" },
  { k:"うちに", t:"g", label:"〜うちに (während / solange noch / bevor)", de:"»solange (noch) … / bevor …« — du nutzt einen Zeitraum, bevor er vorbei ist. (N3)" },
  { k:"だらけ", t:"g", label:"〜だらけ (voller …)", de:"Nomen + だらけ = »voller / übersät mit …«, meist negativ: 血だらけ »voller Blut«. (N3)" },
  { k:"わけには", t:"g", label:"〜わけにはいかない (kann/darf nicht)", de:"»das geht (aus Pflicht/Umständen) nicht« — oft わけにはいかない. (N3)" },
  { k:"気がする", t:"g", label:"〜気がする (das Gefühl haben, dass …)", de:"Plain-Form / N＋の + 気がする = »ich hab so ein Gefühl, dass …« — eine vage Ahnung. (N3)" },
  { k:"気がし", t:"g", label:"〜気がする (das Gefühl haben, dass …)", de:"気がした »ich hatte das Gefühl«, 気がします (höflich). Eine vage Ahnung, ein Eindruck. (N3)" },
  { k:"おかげ", t:"g", label:"〜おかげで (dank …)", de:"Nの／Plain + おかげで = »dank … / weil …« mit gutem Ergebnis (dankbar). (N3)" },
  { k:"せいで", t:"g", label:"〜せいで (wegen … [schlecht])", de:"Nの／Plain + せいで = »wegen …« mit schlechtem Ergebnis (Schuld/Vorwurf). (N3)" },
  { k:"違いない", t:"g", label:"〜に違いない (ganz sicher)", de:"Plain-Form/N + に違いない = »das ist ganz sicher so«. Stärker als はず und かもしれない. (N3)" },
  { k:"ちがいない", t:"g", label:"〜にちがいない (ganz sicher)", de:"»das ist ganz sicher so« (auch in Kana geschrieben). (N3)" },
  { k:"ものか", t:"g", label:"〜ものか (niemals!)", de:"Plain-Form + ものか = trotziger Ausruf, gemeint ist das Gegenteil: 負けるものか »ich verliere ganz sicher NICHT!«. (N3)" },
  { k:"もんか", t:"g", label:"〜もんか (niemals!, ugs.)", de:"Lockere Form von ものか: »auf gar keinen Fall!«. (N3)" },
  { k:"こそ", t:"g", label:"〜こそ (gerade / erst recht)", de:"Hebt das Wort davor mit Nachdruck hervor: 今こそ »jetzt erst recht«, きみこそ »gerade du«. (N3)" },
  { k:"くせに", t:"g", label:"〜くせに (obwohl, vorwurfsvoll)", de:"Wie のに »obwohl«, aber mit Vorwurf/Verachtung: »obwohl er doch …!«. An Plain-Form / Nの. (N3)" },
  { k:"にとって", t:"g", label:"〜にとって (für, aus Sicht von)", de:"»für … / aus Sicht von …«: <ruby>私<rt>わたし</rt></ruby>にとって大切 »für mich wichtig«. (N3)" },
  { k:"ふりを", t:"g", label:"〜ふりをする (so tun, als ob)", de:"Plain-Form/Nの + ふりをする = »so tun, als ob … / sich … stellen«. 寝たふりをする »sich schlafend stellen«. (N3)" },
  { k:"あげく", t:"g", label:"〜あげく(に) (nach langem … schließlich)", de:"た-Form/Nの + あげく: nach langem Vorgang schließlich ein (meist schlechtes) Ergebnis. 悩んだあげく »nach langem Grübeln«. (N3)" },
  { k:"まい", t:"p", nk:false, label:"〜まい (gewiss nicht)", de:"Nachdrücklich: »ich werde ganz sicher NICHT …« (Entschluss) oder »… wohl nicht« (Vermutung). 逃がすまい. (N3)" },
  { k:"ことか", t:"g", label:"〜ことか (wie sehr …!)", de:"Mit Fragewort (どんなに/なんと) + ことか: emotionaler Ausruf »wie sehr …!«, keine echte Frage. (N3)" },
  { k:"てこそ", t:"g", label:"〜てこそ (erst dadurch, dass …)", de:"て-Form + こそ: »erst wenn/dadurch, dass man wirklich … (tut)«. 守ってこそ親だ. (N3)" },
  { k:"っぱなし", t:"g", label:"〜っぱなし (… gelassen / ständig)", de:"Vます-Stamm + っぱなし: man tut etwas und lässt es dann so (oft nachlässig). つけっぱなし »angelassen«, 開けっぱなし »offen gelassen«, 立ちっぱなし »die ganze Zeit gestanden«. (N3)" },
  { k:"どころか", t:"g", label:"〜どころか (von wegen … / im Gegenteil)", de:"V/N + どころか: stellt eine Erwartung auf und reißt sie sofort ein — »von wegen X; in Wirklichkeit (das Gegenteil / viel mehr)«. 休むどころか、もっと いそがしい »von wegen ausruhen — noch mehr Stress«. (N3)" },
  { k:"たきり", t:"g", label:"〜たきり (seit … nichts mehr / nur)", de:"Verb-た + きり: nach der Handlung bleibt die erwartete Folge aus. 出て行ったきり、帰って こない »ging hinaus und kam (seither) nie zurück«; 寝たきり »ans Bett gefesselt«. Auch 〜きり = »nur« (二人きり »nur zu zweit«). (N3)" },
  { k:"ことなく", t:"g", label:"〜ことなく (ohne je zu …)", de:"Verb-Wörterbuchform + ことなく: »ohne (auch nur einmal) zu …«. ふり返る ことなく »ohne sich umzudrehen«; だれにも 知られる ことなく »ohne dass es jemand erfährt«. Schriftsprachlicher als 〜ないで. (N3)" },
  { k:"ください", t:"g", label:"ください (bitte)", de:"Höfliche Bitte »bitte (geben/tun) Sie«. Nach て-Form: 〜てください »bitte tu …«. (L14)" },
  { k:"じゃ", t:"g", label:"じゃ (=では, locker)", de:"Lockere Form von では: »dann/also«; in じゃない »ist nicht«. (gesprochen)" },
  { k:"ぞ", t:"p", nk:false, label:"ぞ (Betonung, derb)", de:"Männlich/derb betonende Endpartikel: »…, sag ich dir!«, »…!«." },
  // --- Häufige Verb-/Kopula-Endungen (damit fast jede Satz-Endung erklärt wird) ---
  { k:"ませんでした", t:"g", label:"〜ませんでした (höflich, Verg. verneint)", de:"Die höfliche, verneinte Vergangenheit: »… (hat) nicht …«. Aus ます → ません → ませんでした." },
  { k:"ましょう", t:"g", label:"〜ましょう (lass uns …)", de:"Höflicher Vorschlag/Aufforderung: »lass uns … (tun)«." },
  { k:"なかった", t:"g", label:"〜なかった (Plain, Verg. verneint)", de:"Verneinte Vergangenheit (Plain): »… (hat) nicht …«. (Bei 少なかった/危なかった gehört es zum Adjektiv: »war wenig/gefährlich«.)" },
  { k:"ません", t:"g", label:"〜ません (höfliche Verneinung)", de:"Die höfliche Verneinung: »… nicht«. Grundform: ます." },
  { k:"ました", t:"g", label:"〜ました (höfliche Vergangenheit)", de:"Die höfliche Vergangenheit: »… (hat) ge…«. Grundform: ます." },
  { k:"でした", t:"g", label:"〜でした (war …)", de:"Höfliche Vergangenheit von です: »war / ist gewesen«." },
  { k:"だった", t:"g", label:"〜だった (war …, Plain)", de:"Plain-Form von です/だ in der Vergangenheit: »war«." },
  { k:"かった", t:"g", label:"〜かった (Vergangenheit)", de:"Vergangenheit eines い-Adjektivs (寒かった »war kalt«, よかった »war gut«) — oder Verb-た-Form nach か (分かった »verstand«)." },
  { k:"ます", t:"g", label:"〜ます (höfliche Form)", de:"Die höfliche Verb-Endung (Gegenwart/Zukunft): »… (tun)«." },
  { k:"です", t:"g", label:"〜です (ist …)", de:"Die höfliche Kopula: »ist / sind«." },
  { k:"った", t:"g", label:"〜った (Plain-Vergangenheit)", de:"Plain-Vergangenheit vieler Verben: 拾った »hob auf«, 言った »sagte«, なった »wurde«." },
  { k:"した", t:"g", label:"〜した (Plain-Vergangenheit)", de:"Plain-Vergangenheit, oft von する-Verben: 勉強した »lernte«, 〜した »tat«." },
  { k:"ない", t:"g", label:"〜ない (Verneinung)", de:"Verneinung (Plain): »… nicht«. Achtung: bei 少ない/危ない/きたない gehört ない zum Adjektiv selbst." },
  { k:"ずには", t:"g", label:"〜ずにはいられない (kann nicht anders als)", de:"»ich kann nicht anders, als zu …« — ein Drang, dem man nicht widersteht. する → せずにはいられない. (N3)" },
  { k:"て", t:"p", nk:true, label:"〜て (て-Form)", de:"Die て-Form: verbindet Sätze »… und dann …« oder hängt Hilfsverben an (〜ている, 〜てください …)." }
];
