// Grammatik-Nachschlagewerk für den Lese-Trainer.
// Beim Antippen einer Sinneinheit wird ihr Text nach diesen Mustern durchsucht.
//   t: 'g' = als Teilzeichenkette suchen (längste zuerst).
//   t: 'p' = nur als ABSCHLUSS-Partikel der Einheit; nk:true = nur wenn Kanji in der Einheit.
window.LESEN_GRAMMAR = [
  // --- Fall-/Themapartikel (am Ende der Sinneinheit) ---
  { k:"は", t:"p", nk:true,  label:"は (Themapartikel)", de:"Markiert das Thema: »was X angeht …«. Wird »wa« gesprochen. (Minna L1)" },
  { k:"が", t:"p", nk:true,  label:"が (Subjekt)", de:"Markiert das Subjekt oder neue/betonte Information. Auch bei 好き/できる/ある. (L4/L8)" },
  { k:"を", t:"p", nk:true,  label:"を (Objekt)", de:"Markiert das direkte Objekt; gesprochen »o«. Bei Bewegungsverben auch die Strecke (橋を渡る). (L6/L23)" },
  { k:"に", t:"p", nk:true,  label:"に (Ziel/Zeit/Ort)", de:"Zielpunkt, Empfänger, fester Zeitpunkt (7時に) oder Existenzort (に いる/ある). (L4/L7/L10)" },
  { k:"へ", t:"p", nk:true,  label:"へ (Richtung)", de:"Bewegungsrichtung »nach/zu«; gesprochen »e«. (L5)" },
  { k:"と", t:"p", nk:true,  label:"と (und/mit/Zitat)", de:"»und« zwischen Nomen, »mit« (Person), oder Zitat-Marker (…と言う). (L4/L5/L21)" },
  { k:"も", t:"p", nk:true,  label:"も (auch)", de:"»auch«; ersetzt は/が/を. Mit Verneinung: »nicht einmal«. (L1)" },
  { k:"の", t:"p", nk:true,  label:"の (Genitiv/Verbindung)", de:"Verbindet zwei Nomen: »N₁s N₂«; auch Nominalisierung. (L1/L38)" },
  { k:"や", t:"p", nk:true,  label:"や (und u.a.)", de:"Verbindet Nomen als unvollständige Aufzählung »… und so weiter«." },
  { k:"か", t:"p", nk:false, label:"か (Frage)", de:"Macht den Satz zur Frage. (L1)" },
  { k:"ね", t:"p", nk:false, label:"ね (nicht wahr?)", de:"Sucht Zustimmung: »…, oder?«." },
  { k:"よ", t:"p", nk:false, label:"よ (Betonung)", de:"Betont eine Information für den Hörer: »ich sag dir …«." },
  // --- mehrzeichige Partikel/Verbindungen ---
  { k:"から", t:"g", label:"から (von/ab/weil)", de:"»von/ab« (Zeit/Ort) ODER »weil« (Grund) am Satzende eines Grundsatzes. (L4/L9)" },
  { k:"まで", t:"g", label:"まで (bis)", de:"»bis« (Zeit/Ort/Zustand). まで に = »bis spätestens«. (L4)" },
  { k:"より", t:"g", label:"より (als)", de:"Vergleich »als«; das Adjektiv bleibt unverändert. (L12)" },
  { k:"など", t:"g", label:"など (usw.)", de:"»und so weiter«, Beispiel-Aufzählung." },
  { k:"だけ", t:"g", label:"だけ (nur)", de:"»nur« (neutral). (L11)" },
  { k:"しか", t:"g", label:"しか …ない (nur)", de:"»nur« mit Verneinung — Beiklang »zu wenig«. (L27)" },
  { k:"ばかり", t:"g", label:"ばかり (nur/gerade erst)", de:"»nur/ständig« oder た+ばかり »gerade erst«. (L46)" },
  // --- Erklärungs-/Stilendungen ---
  { k:"んです", t:"g", label:"んです (Erklärung)", de:"Gibt Grund/Hintergrund: »es ist nämlich so, dass …«. (L26)" },
  { k:"んだ", t:"g", label:"んだ (Erklärung, plain)", de:"Plain-Form von んです: »…, nämlich«. (L20/L26)" },
  { k:"のだ", t:"g", label:"のだ (Erklärung)", de:"Schriftliche Form von んです/んだ." },
  { k:"でしょう", t:"g", label:"でしょう (Vermutung/oder?)", de:"»…wird wohl« (Vermutung) oder mit ?-Ton »…, oder?«. (L32)" },
  { k:"だろう", t:"g", label:"だろう (Vermutung, plain)", de:"Plain-Form von でしょう: »wohl«." },
  // --- て-Form-Anschlüsse ---
  { k:"ています", t:"g", label:"〜ている (Verlauf/Zustand)", de:"»ist gerade dabei« oder anhaltender Zustand. (L14/L15)" },
  { k:"ている", t:"g", label:"〜ている (Verlauf/Zustand)", de:"»ist gerade dabei« / Dauerzustand (plain). (L14/L15)" },
  { k:"でいます", t:"g", label:"〜ている (Verlauf/Zustand)", de:"»ist gerade dabei« / Dauerzustand (で-Laut nach ん/む/ぶ/ぐ). (L14/L15)" },
  { k:"でいる", t:"g", label:"〜ている (Verlauf/Zustand)", de:"»ist gerade dabei« / Dauerzustand (で-Laut, plain). (L14/L15)" },
  { k:"ていまし", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"»war gerade dabei / war im Zustand …«." },
  { k:"ていた", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"Vergangenheit von ている." },
  { k:"でいまし", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"»war gerade dabei …« (で-Laut nach ん/む/ぶ/ぐ)." },
  { k:"でいた", t:"g", label:"〜ていた (Verlauf, Verg.)", de:"Vergangenheit von ている (で-Laut)." },
  { k:"てある", t:"g", label:"〜てある (vorbereitet)", de:"Zustand, den jemand absichtlich herbeigeführt hat. (L30)" },
  { k:"ておく", t:"g", label:"〜ておく (im Voraus)", de:"Etwas vorbereitend/im Voraus erledigen. (L30)" },
  { k:"てしまい", t:"g", label:"〜てしまう (leider/ganz)", de:"Bedauern »leider« oder Vollendung »ganz«. (L29)" },
  { k:"てしまう", t:"g", label:"〜てしまう (leider/ganz)", de:"Bedauern »leider« oder Vollendung »ganz«. (L29)" },
  { k:"てしま", t:"g", label:"〜てしまう (leider/ganz)", de:"Bedauern »leider« oder Vollendung »ganz« (auch てしまった/てしまって). (L29)" },
  { k:"でしま", t:"g", label:"〜てしまう (leider/ganz)", de:"Bedauern »leider« / Vollendung »ganz« (で-Laut: 飲んでしまった …). (L29)" },
  { k:"ちゃっ", t:"g", label:"〜ちゃう (=てしまう, ugs.)", de:"Umgangssprachliche Verschmelzung von てしまう: »… ganz/leider« (飲んじゃった)." },
  { k:"じゃっ", t:"g", label:"〜じゃう (=でしまう, ugs.)", de:"Umgangssprachlich für でしまう (死んじゃった …)." },
  { k:"てくれ", t:"g", label:"〜てくれる (für mich)", de:"Jemand tut etwas (als Gefallen) für mich. (L24)" },
  { k:"てもらえ", t:"g", label:"〜てもらえる (bekommen können)", de:"»ich kann etwas getan bekommen / mir wird getan«. (L24)" },
  { k:"てもらお", t:"g", label:"〜てもらおう (ich lasse …)", de:"»ich werde mir … tun lassen« (Volitional von てもらう). (L24)" },
  { k:"てもらう", t:"g", label:"〜てもらう (sich tun lassen)", de:"Ich lasse jemanden etwas für mich tun / profitiere. (L24)" },
  { k:"てあげ", t:"g", label:"〜てあげる (für andere)", de:"Ich tue jemandem einen Gefallen. (L24)" },
  { k:"ていただ", t:"g", label:"〜ていただく (höflich für mich)", de:"Höflich: jemand (Höhergestellter) tut etwas für mich. (L41)" },
  { k:"てください", t:"g", label:"〜てください (bitte tu)", de:"Höfliche Bitte. (L14)" },
  { k:"てくる", t:"g", label:"〜てくる (her/allmählich)", de:"Bewegung zu mir hin oder Entwicklung bis jetzt. (L43)" },
  { k:"ていく", t:"g", label:"〜ていく (weg/künftig)", de:"Bewegung weg von mir oder Entwicklung in die Zukunft. (L43)" },
  { k:"てもいい", t:"g", label:"〜てもいい (darf)", de:"»darf …«; mit か: um Erlaubnis bitten. (L15)" },
  { k:"てはいけ", t:"g", label:"〜てはいけない (darf nicht)", de:"Verbot »darf nicht«. (L15)" },
  // --- ない-Form-Anschlüsse ---
  { k:"ないで", t:"g", label:"〜ないで (ohne/bitte nicht)", de:"»ohne zu …« oder ないでください »bitte nicht«. (L17/L34)" },
  { k:"なければ", t:"g", label:"〜なければ (muss/wenn nicht)", de:"なければならない »muss«; oder »wenn nicht …«. (L17)" },
  { k:"なくても", t:"g", label:"〜なくてもいい (muss nicht)", de:"»auch ohne … ist's gut« = muss nicht. (L17)" },
  { k:"なくなる", t:"g", label:"〜なくなる (nicht mehr)", de:"»wird nicht mehr …«." },
  { k:"なくなり", t:"g", label:"〜なくなる (nicht mehr)", de:"»wird/wurde nicht mehr …«." },
  // --- Modalität / Vermutung ---
  { k:"かもしれ", t:"g", label:"かもしれない (vielleicht)", de:"»vielleicht / könnte sein«. (L32)" },
  { k:"はず", t:"g", label:"はず (müsste)", de:"Begründete Vermutung »müsste so sein«; はずがない »kann nicht sein«. (L46)" },
  { k:"そう", t:"g", label:"そう (sieht aus / man sagt)", de:"Adj/ますStamm+そう »sieht … aus«; Plain+そう »man sagt«. (L40/L43/L47)" },
  { k:"ようだ", t:"g", label:"ようだ (scheint)", de:"»es scheint, als ob …« (eigene Vermutung). (L47)" },
  { k:"ように", t:"g", label:"ように (wie/damit)", de:"»wie« (Vergleich) oder »damit« (Ziel). (L36)" },
  { k:"ような", t:"g", label:"ような (wie ein …)", de:"»wie ein …« vor einem Nomen. (L47)" },
  { k:"のように", t:"g", label:"のように (wie)", de:"Vergleich »(genau)wie …«." },
  { k:"みたい", t:"g", label:"みたい (wie/scheint)", de:"Umgangssprachlich für ようだ: »wie/scheint«." },
  { k:"らしい", t:"g", label:"らしい (anscheinend)", de:"Vermutung aus (oft fremden) Infos: »anscheinend«." },
  // --- Konditionale / Verbindungen ---
  { k:"たら", t:"g", label:"〜たら (wenn/falls)", de:"Flexibelstes »wenn/falls/nachdem«. (L25)" },
  { k:"なら", t:"g", label:"なら (was … betrifft)", de:"Themenbezogenes »wenn es um … geht«. (L35)" },
  { k:"ても", t:"g", label:"〜ても (auch wenn)", de:"»auch wenn / selbst wenn«. (L25)" },
  { k:"でも", t:"g", label:"でも (auch wenn / oder so)", de:"»auch wenn« (N/な-Adj) oder Vorschlag »… oder so«. (L21/L25)" },
  { k:"のに", t:"g", label:"のに (obwohl)", de:"»obwohl« mit Beiklang von Enttäuschung/Ärger. (L45)" },
  { k:"ので", t:"g", label:"ので (weil)", de:"Höflicher/weicher Grund »da/weil«. (L39)" },
  { k:"けど", t:"g", label:"けど (aber)", de:"Lockeres »aber/zwar«. (L20)" },
  { k:"けれど", t:"g", label:"けれど (aber)", de:"Etwas höflicheres »aber/jedoch«." },
  // --- Verbformen / Hilfskonstruktionen ---
  { k:"なければなり", t:"g", label:"なければならない (muss)", de:"Pflicht: »muss …«. (L17)" },
  { k:"ことができ", t:"g", label:"ことができる (können)", de:"Fähigkeit/Möglichkeit »können«. (L18)" },
  { k:"ことがある", t:"g", label:"〜たことがある (Erfahrung)", de:"»schon einmal getan haben«. (L19)" },
  { k:"ことがあ", t:"g", label:"〜たことがある (Erfahrung)", de:"»schon einmal getan haben« (auch ことがあります/あった). (L19)" },
  { k:"つもり", t:"g", label:"つもり (Absicht)", de:"Feste Absicht »ich habe vor zu …«. (L31)" },
  { k:"ながら", t:"g", label:"〜ながら (während)", de:"Zwei gleichzeitige Handlungen derselben Person. (L28)" },
  { k:"たり", t:"g", label:"〜たり〜たり (mal … mal)", de:"Beispielhafte Aufzählung von Handlungen. (L19)" },
  { k:"ようとし", t:"g", label:"〜ようとする (versuchen)", de:"»versuchen zu … / im Begriff sein«." },
  { k:"ようと", t:"g", label:"〜ようと思う (Vorhaben)", de:"Volitional + と思う = »ich will/habe vor zu …«. (L31)" },
  { k:"させられ", t:"g", label:"使役受身 (gezwungen werden)", de:"Kausativ + Passiv: »ich werde gezwungen, … zu tun« (gegen den Willen). (CK)" },
  { k:"させて", t:"g", label:"使役 (lassen/zwingen) + て", de:"Kausativ-て: »lassen/zwingen«; +ください = um Erlaubnis bitten. (L48)" },
  { k:"させる", t:"g", label:"使役 (lassen/zwingen)", de:"Kausativ: jemanden etwas tun lassen oder dazu zwingen. (L48)" },
  { k:"られ", t:"g", label:"られる (Passiv/Potential/Respekt)", de:"Je nach Kontext: Passiv »wird …«, Potential »kann …« oder höflicher Respekt. (L27/L37/L49)" },
  { k:"れた", t:"g", label:"〜れる (Passiv)", de:"Passiv-Endung (Gr. I): »wurde …«. (L37)" },
  { k:"れて", t:"g", label:"〜れる (Passiv) + て", de:"Passiv in der て-Form. (L37)" },
  { k:"ところ", t:"g", label:"ところ (Moment/gerade)", de:"Phase einer Handlung: gerade dabei / eben fertig. (L46)" },
  { k:"すぎ", t:"g", label:"〜すぎる (zu sehr)", de:"»zu sehr / übermäßig«. (L44)" },
  { k:"やすい", t:"g", label:"〜やすい (leicht zu)", de:"»leicht zu …«. (L44)" },
  { k:"にくい", t:"g", label:"〜にくい (schwer zu)", de:"»schwer zu …«. (L44)" },
  { k:"ほど", t:"g", label:"ほど (so sehr/je…desto)", de:"»so sehr, dass …« oder ば〜ほど »je … desto«. (L35)" },
  { k:"ずに", t:"g", label:"〜ずに (ohne zu)", de:"Schriftsprachlich für ないで: »ohne zu …«. する→せずに. (CK)" },
  { k:"たい", t:"g", label:"〜たい (möchte)", de:"Wunsch »ich möchte … tun«. (L13)" }
];
