// Alltags-Wörterbuch für den Lese-Trainer (Wort-Antippen).
// Wird mit den Kapitel-Vokabeln zusammengeführt; deckt die häufigsten
// Wörter der Texte ab, damit beim Antippen fast immer eine Übersetzung erscheint.
// Format wie bei vokabeln: { w:"漢字 (かな)" | "かな", de:"…" }.
window.LESEN_WOERTER = [
  // --- Menschen / Pronomen ---
  { w:"私 (わたし)", de:"ich" },
  { w:"僕 (ぼく)", de:"ich (männlich, locker)" },
  { w:"きみ", de:"du" },
  { w:"あなた", de:"Sie, du" },
  { w:"自分 (じぶん)", de:"man selbst, sich" },
  { w:"友達 (ともだち)", de:"Freund/in" },
  { w:"母 (はは)", de:"(eigene) Mutter" },
  { w:"お母さん (おかあさん)", de:"Mutter, Mama" },
  { w:"父 (ちち)", de:"(eigener) Vater" },
  { w:"お父さん (おとうさん)", de:"Vater, Papa" },
  { w:"おじいさん", de:"Großvater; alter Mann" },
  { w:"子ども (こども)", de:"Kind" },
  { w:"人 (ひと)", de:"Mensch, Person" },
  { w:"人間 (にんげん)", de:"Mensch" },
  { w:"男 (おとこ)", de:"Mann" },
  { w:"女 (おんな)", de:"Frau" },
  { w:"みんな", de:"alle" },
  // --- Verben ---
  { w:"言う (いう)", de:"sagen" },
  { w:"話す (はなす)", de:"sprechen, erzählen" },
  { w:"聞く (きく)", de:"hören; fragen" },
  { w:"聞こえる (きこえる)", de:"zu hören sein, ertönen" },
  { w:"見る (みる)", de:"sehen, schauen" },
  { w:"見える (みえる)", de:"zu sehen sein, erscheinen" },
  { w:"見つける (みつける)", de:"finden, entdecken" },
  { w:"見つめる (みつめる)", de:"anstarren, fixieren" },
  { w:"見上げる (みあげる)", de:"hinaufblicken" },
  { w:"見合わせる (みあわせる)", de:"einander ansehen" },
  { w:"行く (いく)", de:"gehen" },
  { w:"来る (くる)", de:"kommen" },
  { w:"帰る (かえる)", de:"zurückkehren, heimgehen" },
  { w:"歩く (あるく)", de:"gehen, zu Fuß gehen" },
  { w:"走る (はしる)", de:"rennen, laufen" },
  { w:"進む (すすむ)", de:"vorangehen, fortschreiten" },
  { w:"登る (のぼる)", de:"hinaufsteigen, klettern" },
  { w:"渡る (わたる)", de:"überqueren, hinübergehen" },
  { w:"立つ (たつ)", de:"stehen, sich stellen" },
  { w:"立ち上がる (たちあがる)", de:"aufstehen" },
  { w:"座る (すわる)", de:"sich setzen" },
  { w:"入る (はいる)", de:"hineingehen, eintreten" },
  { w:"出る (でる)", de:"hinausgehen, herauskommen" },
  { w:"出す (だす)", de:"herausnehmen, herausholen" },
  { w:"取り出す (とりだす)", de:"herausholen, hervorholen" },
  { w:"通る (とおる)", de:"durchgehen, passieren" },
  { w:"近づく (ちかづく)", de:"sich nähern" },
  { w:"向かう (むかう)", de:"sich hinwenden, zusteuern" },
  { w:"向ける (むける)", de:"richten auf" },
  { w:"追いかける (おいかける)", de:"verfolgen, nachjagen" },
  { w:"逃げる (にげる)", de:"fliehen, weglaufen" },
  { w:"逃がす (にがす)", de:"entkommen lassen" },
  { w:"隠れる (かくれる)", de:"sich verstecken" },
  { w:"取る (とる)", de:"nehmen, greifen" },
  { w:"持つ (もつ)", de:"halten, haben, tragen" },
  { w:"待つ (まつ)", de:"warten" },
  { w:"食べる (たべる)", de:"essen" },
  { w:"飲む (のむ)", de:"trinken" },
  { w:"飲み込む (のみこむ)", de:"verschlingen, hinunterschlucken" },
  { w:"作る (つくる)", de:"machen, herstellen, kochen" },
  { w:"思う (おもう)", de:"denken, glauben, finden" },
  { w:"思い出す (おもいだす)", de:"sich erinnern" },
  { w:"知る (しる)", de:"wissen, kennen(lernen)" },
  { w:"わかる", de:"verstehen, begreifen" },
  { w:"考える (かんがえる)", de:"nachdenken, überlegen" },
  { w:"決める (きめる)", de:"entscheiden, beschließen" },
  { w:"信じる (しんじる)", de:"glauben, vertrauen" },
  { w:"守る (まもる)", de:"beschützen, verteidigen" },
  { w:"助ける (たすける)", de:"helfen, retten" },
  { w:"探す (さがす)", de:"suchen" },
  { w:"開ける (あける)", de:"öffnen" },
  { w:"開く (ひらく)", de:"sich öffnen, aufgehen" },
  { w:"閉める (しめる)", de:"schließen, zumachen" },
  { w:"笑う (わらう)", de:"lachen, lächeln" },
  { w:"泣く (なく)", de:"weinen" },
  { w:"叫ぶ (さけぶ)", de:"schreien, rufen" },
  { w:"消える (きえる)", de:"verschwinden, erlöschen" },
  { w:"消す (けす)", de:"löschen, ausmachen" },
  { w:"光る (ひかる)", de:"leuchten, glänzen" },
  { w:"動く (うごく)", de:"sich bewegen" },
  { w:"変わる (かわる)", de:"sich verändern" },
  { w:"変える (かえる)", de:"verändern, ändern" },
  { w:"終わる (おわる)", de:"enden, zu Ende gehen" },
  { w:"始める (はじめる)", de:"beginnen, anfangen" },
  { w:"始まる (はじまる)", de:"beginnen, losgehen" },
  { w:"続く (つづく)", de:"andauern, weitergehen" },
  { w:"落ちる (おちる)", de:"fallen, herunterfallen" },
  { w:"残る (のこる)", de:"übrig bleiben, zurückbleiben" },
  { w:"覚える (おぼえる)", de:"sich merken, lernen" },
  { w:"願う (ねがう)", de:"bitten, wünschen" },
  { w:"感じる (かんじる)", de:"fühlen, empfinden" },
  { w:"休む (やすむ)", de:"sich ausruhen, Pause machen" },
  { w:"疲れる (つかれる)", de:"müde werden, erschöpft sein" },
  { w:"上がる (あがる)", de:"hinaufgehen, steigen" },
  { w:"上げる (あげる)", de:"heben, hochheben; geben" },
  { w:"下がる (さがる)", de:"sinken, zurückweichen" },
  { w:"現れる (あらわれる)", de:"erscheinen, auftauchen" },
  { w:"浮かぶ (うかぶ)", de:"auftauchen, in den Sinn kommen" },
  { w:"流れる (ながれる)", de:"fließen, strömen" },
  { w:"流れ込む (ながれこむ)", de:"hineinströmen" },
  { w:"当たる (あたる)", de:"treffen, auftreffen" },
  { w:"つかむ", de:"packen, ergreifen" },
  { w:"ふれる", de:"berühren" },
  { w:"ささやく", de:"flüstern" },
  { w:"うなずく", de:"nicken" },
  { w:"ふるえる", de:"zittern, beben" },
  { w:"だます", de:"täuschen, betrügen" },
  { w:"ねらう", de:"es abgesehen haben auf, zielen" },
  { w:"くずれる (崩れる)", de:"zerfallen, einstürzen" },
  { w:"とける (溶ける)", de:"sich auflösen, schmelzen" },
  { w:"つつむ (包む)", de:"einhüllen, umhüllen" },
  { w:"響く (ひびく)", de:"hallen, widerhallen" },
  { w:"せまる (迫る)", de:"heranrücken, bedrängen" },
  { w:"おびえる", de:"sich ängstigen, erschrecken" },
  { w:"固まる (かたまる)", de:"erstarren, hart werden" },
  { w:"こらえる", de:"zurückhalten, unterdrücken" },
  { w:"疑う (うたがう)", de:"zweifeln, misstrauen" },
  { w:"のぞく", de:"hineinschauen, spähen" },
  { w:"あきらめる", de:"aufgeben, resignieren" },
  { w:"まかせる (任せる)", de:"überlassen, anvertrauen" },
  { w:"失う (うしなう)", de:"verlieren" },
  { w:"似る (にる)", de:"ähneln, ähnlich sein" },
  { w:"つぶやく", de:"murmeln, vor sich hin sagen" },
  { w:"黙る (だまる)", de:"schweigen, still sein" },
  { w:"つかまる", de:"gefasst/gepackt werden" },
  { w:"たどり着く (たどりつく)", de:"(mühsam) ankommen, erreichen" },
  { w:"通り過ぎる (とおりすぎる)", de:"vorbeiziehen, vorbeigehen" },
  { w:"聞き返す (ききかえす)", de:"zurückfragen, nachfragen" },
  // --- i-Adjektive ---
  { w:"大きい (おおきい)", de:"groß" },
  { w:"小さい (ちいさい)", de:"klein" },
  { w:"高い (たかい)", de:"hoch; teuer" },
  { w:"低い (ひくい)", de:"niedrig; tief (Stimme)" },
  { w:"長い (ながい)", de:"lang" },
  { w:"短い (みじかい)", de:"kurz" },
  { w:"古い (ふるい)", de:"alt (Dinge)" },
  { w:"新しい (あたらしい)", de:"neu" },
  { w:"暗い (くらい)", de:"dunkel" },
  { w:"明るい (あかるい)", de:"hell" },
  { w:"寒い (さむい)", de:"kalt (Wetter)" },
  { w:"冷たい (つめたい)", de:"kalt (Berührung), kühl" },
  { w:"重い (おもい)", de:"schwer" },
  { w:"軽い (かるい)", de:"leicht" },
  { w:"強い (つよい)", de:"stark" },
  { w:"弱い (よわい)", de:"schwach" },
  { w:"早い (はやい)", de:"früh; schnell" },
  { w:"遅い (おそい)", de:"spät; langsam" },
  { w:"多い (おおい)", de:"viel, zahlreich" },
  { w:"少ない (すくない)", de:"wenig" },
  { w:"こわい (怖い)", de:"angsteinflößend, gruselig" },
  { w:"痛い (いたい)", de:"schmerzhaft, wehtun" },
  { w:"おもしろい", de:"interessant, lustig" },
  { w:"うれしい", de:"froh, erfreut" },
  { w:"悲しい (かなしい)", de:"traurig" },
  { w:"楽しい (たのしい)", de:"vergnüglich, schön" },
  { w:"欲しい (ほしい)", de:"haben wollen, sich wünschen" },
  { w:"細い (ほそい)", de:"dünn, schmal" },
  { w:"鋭い (するどい)", de:"scharf, durchdringend" },
  { w:"深い (ふかい)", de:"tief" },
  { w:"濃い (こい)", de:"dicht, intensiv" },
  { w:"やさしい", de:"sanft, freundlich; leicht" },
  { w:"すごい", de:"toll, gewaltig, krass" },
  { w:"おかしい", de:"seltsam; komisch" },
  // --- na-Adjektive / Zustände ---
  { w:"静か (しずか)", de:"still, ruhig" },
  { w:"きれい", de:"schön, hübsch; sauber" },
  { w:"大好き (だいすき)", de:"sehr gern mögen" },
  { w:"大切 (たいせつ)", de:"wichtig, wertvoll" },
  { w:"大変 (たいへん)", de:"schlimm, anstrengend; sehr" },
  { w:"平気 (へいき)", de:"unbesorgt, „kein Problem“" },
  { w:"自由 (じゆう)", de:"frei; Freiheit" },
  { w:"完全 (かんぜん)", de:"vollständig, völlig" },
  { w:"必死 (ひっし)", de:"verzweifelt, mit aller Kraft" },
  { w:"正直 (しょうじき)", de:"ehrlich" },
  { w:"巨大 (きょだい)", de:"riesig, gewaltig" },
  { w:"元気 (げんき)", de:"munter, gesund, voller Energie" },
  { w:"不安 (ふあん)", de:"unruhig, besorgt; Sorge" },
  { w:"大丈夫 (だいじょうぶ)", de:"in Ordnung, alles okay" },
  { w:"確実 (かくじつ)", de:"sicher, gewiss" },
  { w:"無理 (むり)", de:"unmöglich; mit Zwang" },
  // --- Natur / Welt ---
  { w:"学校 (がっこう)", de:"Schule" },
  { w:"大学 (だいがく)", de:"Universität" },
  { w:"学生 (がくせい)", de:"Student/in, Schüler/in" },
  { w:"家 (いえ)", de:"Haus, Zuhause" },
  { w:"部屋 (へや)", de:"Zimmer, Raum" },
  { w:"道 (みち)", de:"Weg, Straße" },
  { w:"町 (まち)", de:"Stadt, Ort" },
  { w:"村 (むら)", de:"Dorf" },
  { w:"世界 (せかい)", de:"Welt" },
  { w:"場所 (ばしょ)", de:"Ort, Platz" },
  { w:"山 (やま)", de:"Berg" },
  { w:"川 (かわ)", de:"Fluss" },
  { w:"森 (もり)", de:"Wald" },
  { w:"木 (き)", de:"Baum, Holz" },
  { w:"草 (くさ)", de:"Gras" },
  { w:"花 (はな)", de:"Blume" },
  { w:"鳥 (とり)", de:"Vogel" },
  { w:"水 (みず)", de:"Wasser" },
  { w:"風 (かぜ)", de:"Wind" },
  { w:"空 (そら)", de:"Himmel" },
  { w:"月 (つき)", de:"Mond" },
  { w:"太陽 (たいよう)", de:"Sonne" },
  { w:"星 (ほし)", de:"Stern" },
  { w:"光 (ひかり)", de:"Licht" },
  { w:"闇 (やみ)", de:"Finsternis, Dunkelheit" },
  { w:"影 (かげ)", de:"Schatten" },
  { w:"石 (いし)", de:"Stein" },
  { w:"火 (ひ)", de:"Feuer" },
  { w:"音 (おと)", de:"Geräusch, Klang" },
  { w:"声 (こえ)", de:"Stimme" },
  // --- Körper ---
  { w:"顔 (かお)", de:"Gesicht" },
  { w:"目 (め)", de:"Auge" },
  { w:"口 (くち)", de:"Mund" },
  { w:"手 (て)", de:"Hand" },
  { w:"足 (あし)", de:"Bein, Fuß" },
  { w:"首 (くび)", de:"Hals" },
  { w:"体 (からだ)", de:"Körper" },
  { w:"心 (こころ)", de:"Herz, Gemüt" },
  { w:"頭 (あたま)", de:"Kopf" },
  { w:"心臓 (しんぞう)", de:"Herz (Organ)" },
  { w:"指 (ゆび)", de:"Finger" },
  { w:"指先 (ゆびさき)", de:"Fingerspitze" },
  { w:"肩 (かた)", de:"Schulter" },
  { w:"むね (胸)", de:"Brust" },
  { w:"血 (ち)", de:"Blut" },
  { w:"なみだ (涙)", de:"Träne" },
  { w:"あせ (汗)", de:"Schweiß" },
  { w:"こぶし", de:"Faust" },
  { w:"ひたい", de:"Stirn" },
  { w:"ほほ", de:"Wange" },
  // --- Dinge / Orte ---
  { w:"力 (ちから)", de:"Kraft, Stärke" },
  { w:"気持ち (きもち)", de:"Gefühl, Stimmung" },
  { w:"気配 (けはい)", de:"Anzeichen, Aura, Präsenz" },
  { w:"表情 (ひょうじょう)", de:"Gesichtsausdruck, Miene" },
  { w:"様子 (ようす)", de:"Zustand, Erscheinung" },
  { w:"言葉 (ことば)", de:"Wort(e), Sprache" },
  { w:"名前 (なまえ)", de:"Name" },
  { w:"意味 (いみ)", de:"Bedeutung, Sinn" },
  { w:"約束 (やくそく)", de:"Versprechen" },
  { w:"夢 (ゆめ)", de:"Traum" },
  { w:"神社 (じんじゃ)", de:"(Shinto-)Schrein" },
  { w:"寺 (てら)", de:"Tempel" },
  { w:"門 (もん)", de:"Tor" },
  { w:"扉 (とびら)", de:"Tür, Pforte" },
  { w:"窓 (まど)", de:"Fenster" },
  { w:"階段 (かいだん)", de:"Treppe" },
  { w:"時計 (とけい)", de:"Uhr" },
  { w:"池 (いけ)", de:"Teich" },
  { w:"鏡 (かがみ)", de:"Spiegel" },
  { w:"箱 (はこ)", de:"Schachtel, Kiste" },
  { w:"井戸 (いど)", de:"Brunnen" },
  { w:"地面 (じめん)", de:"Boden, Erde" },
  { w:"頂上 (ちょうじょう)", de:"Gipfel" },
  { w:"王 (おう)", de:"König" },
  { w:"竜 (りゅう)", de:"Drache" },
  { w:"かけら", de:"Bruchstück, Splitter" },
  { w:"きり (霧)", de:"Nebel" },
  { w:"わな (罠)", de:"Falle" },
  // --- Zeit ---
  { w:"朝 (あさ)", de:"Morgen" },
  { w:"夜 (よる)", de:"Nacht" },
  { w:"夕方 (ゆうがた)", de:"Abend(dämmerung)" },
  { w:"毎日 (まいにち)", de:"jeden Tag" },
  { w:"今 (いま)", de:"jetzt" },
  { w:"今日 (きょう)", de:"heute" },
  { w:"時 (とき)", de:"Zeit, Moment, als …" },
  { w:"前 (まえ)", de:"vorne; vorher, vor" },
  { w:"後ろ (うしろ)", de:"hinten, hinter" },
  { w:"中 (なか)", de:"Inneres, in, Mitte" },
  { w:"上 (うえ)", de:"oben, auf, über" },
  { w:"下 (した)", de:"unten, unter" },
  { w:"横 (よこ)", de:"Seite, neben" },
  { w:"奥 (おく)", de:"hinterer Teil, Tiefe" },
  { w:"間 (あいだ)", de:"Zwischenraum; während" },
  { w:"真ん中 (まんなか)", de:"Mitte, Zentrum" },
  { w:"一番 (いちばん)", de:"am meisten, Nummer eins" },
  { w:"半分 (はんぶん)", de:"Hälfte, halb" },
  // --- Adverbien / Verbindungen ---
  { w:"とても", de:"sehr" },
  { w:"もっと", de:"mehr, noch" },
  { w:"ずっと", de:"die ganze Zeit; weitaus" },
  { w:"やっと", de:"endlich, mit Mühe" },
  { w:"すぐ", de:"sofort, gleich, gleich daneben" },
  { w:"きっと", de:"bestimmt, sicher" },
  { w:"ゆっくり", de:"langsam, gemütlich" },
  { w:"そっと", de:"leise, sachte, vorsichtig" },
  { w:"急に (きゅうに)", de:"plötzlich" },
  { w:"思わず (おもわず)", de:"unwillkürlich, unwillentlich" },
  { w:"とつぜん (突然)", de:"plötzlich, auf einmal" },
  { w:"少し (すこし)", de:"ein wenig, etwas" },
  { w:"ぜんぶ (全部)", de:"alles, ganz" },
  { w:"本当に (ほんとうに)", de:"wirklich" },
  { w:"確かに (たしかに)", de:"tatsächlich, gewiss" },
  { w:"なぜか", de:"aus irgendeinem Grund" },
  { w:"しばらく", de:"eine Weile" },
  { w:"だんだん", de:"allmählich, nach und nach" },
  { w:"やがて", de:"bald, schließlich" },
  { w:"ちょうど", de:"genau, gerade" },
  { w:"ほとんど", de:"fast, beinahe" },
  { w:"何とか (なんとか)", de:"irgendwie, mit Mühe und Not" },
  { w:"まるで", de:"geradeso (wie), ganz wie" },
  { w:"すっかり", de:"völlig, ganz und gar" },
  { w:"かすかに", de:"schwach, kaum merklich" },
  { w:"むしろ", de:"eher, vielmehr" },
  { w:"うっかり", de:"versehentlich, aus Unachtsamkeit" },
  { w:"いっしょに (一緒に)", de:"zusammen, gemeinsam" },
  // --- weitere Alltagsnomen ---
  { w:"日本 (にほん)", de:"Japan" },
  { w:"日本語 (にほんご)", de:"Japanisch (Sprache)" },
  { w:"英語 (えいご)", de:"Englisch" },
  { w:"国 (くに)", de:"Land, Heimat" },
  { w:"東京 (とうきょう)", de:"Tokio" },
  { w:"京都 (きょうと)", de:"Kyoto" },
  { w:"雨 (あめ)", de:"Regen" },
  { w:"雪 (ゆき)", de:"Schnee" },
  { w:"駅 (えき)", de:"Bahnhof" },
  { w:"公園 (こうえん)", de:"Park" },
  { w:"会社 (かいしゃ)", de:"Firma, Unternehmen" },
  { w:"仕事 (しごと)", de:"Arbeit, Beruf" },
  { w:"写真 (しゃしん)", de:"Foto" },
  { w:"本 (ほん)", de:"Buch" },
  { w:"先生 (せんせい)", de:"Lehrer/in, Meister/in" },
  { w:"明日 (あした)", de:"morgen" },
  { w:"昨日 (きのう)", de:"gestern" },
  { w:"今朝 (けさ)", de:"heute Morgen" },
  { w:"毎朝 (まいあさ)", de:"jeden Morgen" },
  { w:"ごはん", de:"Essen, gekochter Reis" },
  { w:"食べ物 (たべもの)", de:"Essen, Speise" },
  { w:"飲み物 (のみもの)", de:"Getränk" },
  { w:"漢字 (かんじ)", de:"Kanji, Schriftzeichen" },
  { w:"手紙 (てがみ)", de:"Brief" },
  { w:"お礼 (おれい)", de:"Dank, Dankesgruß" },
  { w:"相談 (そうだん)", de:"Beratung, Rücksprache" },
  { w:"質問 (しつもん)", de:"Frage" },
  { w:"時間 (じかん)", de:"Zeit, Stunde" },
  { w:"来年 (らいねん)", de:"nächstes Jahr" },
  { w:"来週 (らいしゅう)", de:"nächste Woche" },
  { w:"先週 (せんしゅう)", de:"letzte Woche" },
  { w:"週末 (しゅうまつ)", de:"Wochenende" },
  { w:"誕生日 (たんじょうび)", de:"Geburtstag" },
  { w:"旅行 (りょこう)", de:"Reise" },
  { w:"買い物 (かいもの)", de:"Einkaufen" },
  { w:"新幹線 (しんかんせん)", de:"Shinkansen (Schnellzug)" },
  { w:"電車 (でんしゃ)", de:"Zug, Bahn" },
  { w:"車 (くるま)", de:"Auto" },
  { w:"飛行機 (ひこうき)", de:"Flugzeug" },
  { w:"かばん", de:"Tasche, Schultasche" },
  { w:"プレゼント", de:"Geschenk" },
  // --- Lehnwörter ---
  { w:"デパート", de:"Kaufhaus" },
  { w:"スーパー", de:"Supermarkt" },
  { w:"アパート", de:"(Miet-)Wohnung, Apartment" },
  { w:"ノート", de:"Heft, Notizbuch" },
  { w:"ピアノ", de:"Klavier" },
  { w:"ドア", de:"Tür" },
  { w:"テレビ", de:"Fernseher" },
  { w:"ポケット", de:"(Hosen-)Tasche" },
  { w:"コンビニ", de:"Convenience Store" },
  // --- gängige Verben (Grundform) ---
  { w:"なる", de:"werden, sich verwandeln in" },
  { w:"ある", de:"(es) gibt, vorhanden sein (Dinge)" },
  { w:"いる", de:"da sein, sich aufhalten (Lebewesen)" },
  { w:"する", de:"tun, machen" },
  { w:"できる", de:"können; fertig werden, entstehen" },
  { w:"乗る (のる)", de:"einsteigen, fahren (mit)" },
  { w:"撮る (とる)", de:"(ein Foto) machen, aufnehmen" },
  { w:"降る (ふる)", de:"(Regen/Schnee) fallen" },
  { w:"働く (はたらく)", de:"arbeiten" },
  { w:"飾る (かざる)", de:"schmücken, dekorieren" },
  { w:"教える (おしえる)", de:"lehren, beibringen, sagen" },
  { w:"勉強する (べんきょうする)", de:"lernen, studieren" },
  // --- Adverbien / Demonstrativa / Floskeln ---
  { w:"たくさん", de:"viel, eine Menge" },
  { w:"ちょっと", de:"ein bisschen, kurz" },
  { w:"いつも", de:"immer" },
  { w:"よく", de:"oft; gut" },
  { w:"たぶん", de:"wahrscheinlich, vielleicht" },
  { w:"やっぱり", de:"doch, wie erwartet" },
  { w:"ぜひ", de:"unbedingt, auf jeden Fall" },
  { w:"その", de:"dieser/jener (bekannt)" },
  { w:"この", de:"dieser (hier)" },
  { w:"あの", de:"jener (dort)" },
  { w:"どうぞ", de:"bitte (sehr)" },
  { w:"よろしく", de:"Grußformel: „bitte um Ihr Wohlwollen“" },
  { w:"ありがとう", de:"danke" },
  { w:"はじめまして", de:"Guten Tag (beim ersten Treffen)" },
  { w:"こう", de:"so, auf diese Weise" },
  { w:"なぜ", de:"warum" },
  { w:"いったい", de:"eigentlich, um alles in der Welt" },
  { w:"いっぱい", de:"voll; viel" },
  { w:"分かる (わかる)", de:"verstehen, klar werden" },
  { w:"着る (きる)", de:"anziehen, tragen" },
  { w:"使う (つかう)", de:"benutzen, verwenden" },
  { w:"買う (かう)", de:"kaufen" },
  { w:"会う (あう)", de:"(jemanden) treffen" },
  { w:"歌う (うたう)", de:"singen" },
  { w:"立ち止まる (たちどまる)", de:"stehen bleiben, innehalten" },
  // --- Eigennamen der Geschichten ---
  { w:"レン", de:"Ren (Junge, Hauptfigur der Fantasy-Geschichte)" },
  { w:"ソラ", de:"Sora (kleiner Drache, Rens Begleiter)" },
  { w:"アンナ", de:"Anna (Vorname)" },
  { w:"ユキ", de:"Yuki (Oberschülerin, Horror-Geschichte)" },
  // --- Nachtrag: weitere häufige Wörter ---
  { w:"映画 (えいが)", de:"Film" },
  { w:"服 (ふく)", de:"Kleidung" },
  { w:"授業 (じゅぎょう)", de:"Unterricht" },
  { w:"何 (なに)", de:"was" },
  { w:"ページ", de:"Seite (im Buch)" },
  { w:"急ぐ (いそぐ)", de:"sich beeilen, eilen" },
  { w:"止まる (とまる)", de:"anhalten, stehen bleiben" },
  { w:"忘れる (わすれる)", de:"vergessen" },
  { w:"振る (ふる)", de:"schütteln, winken" },
  { w:"かかる", de:"dauern; (auf-)hängen; (Zeit/Geld) kosten" },
  { w:"震える (ふるえる)", de:"zittern, beben" },
  { w:"海 (うみ)", de:"Meer, See" },
  { w:"氷 (こおり)", de:"Eis" },
  { w:"船 (ふね)", de:"Schiff, Boot" },
  { w:"温かい (あたたかい)", de:"warm" },
  { w:"温める (あたためる)", de:"wärmen, aufwärmen" },
  { w:"集める (あつめる)", de:"sammeln" },
  { w:"スープ", de:"Suppe" },
  { w:"おばあさん", de:"alte Frau, Großmutter" },
  { w:"希望 (きぼう)", de:"Hoffnung" },
  { w:"城 (しろ)", de:"Schloss, Burg" },
  { w:"庭 (にわ)", de:"Garten" },
  { w:"土地 (とち)", de:"Land, Gegend, Grundstück" },
  { w:"立ち向かう (たちむかう)", de:"sich stellen, entgegentreten" },
  { w:"炎 (ほのお)", de:"Flamme" },
  { w:"生き物 (いきもの)", de:"Lebewesen" },
  { w:"ばけもの (化け物)", de:"Ungeheuer, Monster" },
  { w:"戦い (たたかい)", de:"Kampf, Schlacht" },
  { w:"戦う (たたかう)", de:"kämpfen" },
  { w:"育つ (そだつ)", de:"aufwachsen, heranwachsen" },
  { w:"意識 (いしき)", de:"Bewusstsein" },
  { w:"にくむ (憎む)", de:"hassen" },
  { w:"みとめる (認める)", de:"anerkennen, zugeben" },
  { w:"だきしめる (抱きしめる)", de:"fest umarmen" },
  { w:"すがた (姿)", de:"Gestalt, Erscheinung" },
  { w:"ころがる (転がる)", de:"rollen; daliegen" },
  { w:"調べる (しらべる)", de:"untersuchen, nachprüfen" },
  { w:"さびしい (寂しい)", de:"einsam, verlassen" },
  { w:"近所 (きんじょ)", de:"Nachbarschaft, Umgebung" },
  { w:"中身 (なかみ)", de:"Inhalt" },
  { w:"共通点 (きょうつうてん)", de:"Gemeinsamkeit" },
  { w:"すくう (救う)", de:"retten, erretten" },
  { w:"えらぶ (選ぶ)", de:"auswählen, wählen" },
  { w:"オルゴール", de:"Spieluhr, Spieldose" },
  { w:"一人暮らし (ひとりぐらし)", de:"das Alleinleben" },
  { w:"電気 (でんき)", de:"Strom; (elektrisches) Licht" },
  { w:"電話 (でんわ)", de:"Telefon; Anruf" },
  { w:"会社 (かいしゃ)", de:"Firma, Unternehmen" },
  { w:"鳴る (なる)", de:"klingeln, ertönen, läuten" },
  { w:"つれる (連れる)", de:"(jmdn.) mitnehmen, begleiten" },
  { w:"銃 (じゅう)", de:"Pistole, Schusswaffe" },
  { w:"なかま (仲間)", de:"Gefährte, Gleichgesinnter" },
  { w:"別れる (わかれる)", de:"sich trennen, auseinandergehen" },
  { w:"いかり (怒り)", de:"Zorn, Wut" },
  { w:"たいほ (逮捕)", de:"Festnahme, Verhaftung" },
  { w:"しせつ (施設)", de:"Einrichtung, Heim" },
  { w:"しょうこ (証拠)", de:"Beweis, Beleg" },
  { w:"おもちゃ", de:"Spielzeug" },
  { w:"ふりむく (振り向く)", de:"sich umdrehen, zurückblicken" },
  { w:"おくる (送る)", de:"schicken, senden; begleiten" },
  { w:"雨 (あめ)", de:"Regen" },
  { w:"刑事 (けいじ)", de:"Kriminalbeamter, Ermittler" },
  { w:"事件 (じけん)", de:"Fall, Vorfall, Verbrechen" },
  { w:"犯人 (はんにん)", de:"Täter, Schuldiger" },
  { w:"警察 (けいさつ)", de:"Polizei" },
  { w:"殺す (ころす)", de:"töten" },
  { w:"殺人 (さつじん)", de:"Mord" },
  { w:"人形 (にんぎょう)", de:"Puppe" },
  { w:"女性 (じょせい)", de:"Frau (formell)" },
  { w:"事 (こと)", de:"Sache, Angelegenheit; Nominalisierung" },
  { w:"つかまえる (捕まえる)", de:"fangen, festnehmen, schnappen" },
  { w:"おそろしい (恐ろしい)", de:"entsetzlich, furchtbar" },
  { w:"そっくり", de:"zum Verwechseln ähnlich" },
  // --- Farben & weitere Inhaltswörter (Lücken aus den Geschichten) ---
  { w:"黒い (くろい)", de:"schwarz" },
  { w:"赤い (あかい)", de:"rot" },
  { w:"青い (あおい)", de:"blau" },
  { w:"白い (しろい)", de:"weiß" },
  { w:"青白い (あおじろい)", de:"fahlblau, blass" },
  { w:"真っ白 (まっしろ)", de:"schneeweiß, ganz weiß" },
  { w:"真っ赤 (まっか)", de:"tiefrot, knallrot" },
  { w:"真っ青 (まっさお)", de:"kreidebleich; tiefblau" },
  { w:"銀色 (ぎんいろ)", de:"silbern, Silberfarbe" },
  { w:"灰色 (はいいろ)", de:"grau" },
  { w:"生まれる (うまれる)", de:"geboren werden, entstehen" },
  { w:"最後 (さいご)", de:"der/das Letzte, zuletzt" },
  { w:"最初 (さいしょ)", de:"der/das Erste, zuerst" },
  { w:"自身 (じしん)", de:"selbst, persönlich" },
  { w:"一緒 (いっしょ)", de:"zusammen, gemeinsam" },
  { w:"枝 (えだ)", de:"Ast, Zweig" },
  { w:"岩 (いわ)", de:"Fels, Felsen" },
  { w:"者 (もの)", de:"Person, derjenige (der …)" },
  { w:"そば", de:"Nähe, Seite (neben)" },
  { w:"ひま (暇)", de:"freie Zeit, Muße" },
  { w:"ほう (方)", de:"Richtung, Seite" },
  { w:"うち", de:"Inneres; von … (Auswahl); während" },
  { w:"まだ", de:"noch; noch nicht" },
  { w:"はっと", de:"zusammenfahren, aufschrecken (はっとする)" },
  { w:"ぞっと", de:"erschaudern, Gänsehaut (ぞっとする)" },
  { w:"ふと", de:"plötzlich, unwillkürlich" },
  { w:"一つ (ひとつ)", de:"eins (Ding); ein …" },
  { w:"二つ (ふたつ)", de:"zwei (Dinge)" },
  { w:"三つ (みっつ)", de:"drei (Dinge)" },
  { w:"四つ (よっつ)", de:"vier (Dinge)" },
  { w:"五つ (いつつ)", de:"fünf (Dinge)" },
  { w:"六つ (むっつ)", de:"sechs (Dinge)" },
  { w:"七つ (ななつ)", de:"sieben (Dinge)" },
  // --- Kana-Schreibungen & weitere Lückenfüller ---
  { w:"こと", de:"Sache, Angelegenheit; nominalisiert ein Verb" },
  { w:"とき", de:"Zeit; als, wenn (Zeitpunkt)" },
  { w:"もう", de:"schon; (mit Verneinung) nicht mehr" },
  { w:"そこ", de:"dort, da" },
  { w:"ここ", de:"hier" },
  { w:"ぼく", de:"ich (männlich, locker)" },
  { w:"そと (外)", de:"draußen, außen, das Äußere" },
  { w:"子 (こ)", de:"Kind" },
  { w:"方 (ほう)", de:"Richtung, Seite" },
  { w:"引く (ひく)", de:"ziehen; (Farbe) weichen" },
  { w:"当てる (あてる)", de:"drücken an; (er)raten, treffen" },
  { w:"つく", de:"anhaften; (Licht) angehen; (息を)つく seufzen" },
  { w:"熱い (あつい)", de:"heiß" },
  { w:"まぶしい", de:"blendend, grell" },
  { w:"なでる (撫でる)", de:"streicheln, (sanft) streichen" },
  { w:"過ぎる (すぎる)", de:"vergehen; vorbeigehen; zu sehr" },
  { w:"伸ばす (のばす)", de:"ausstrecken, verlängern" },
  { w:"苦しい (くるしい)", de:"qualvoll, schmerzhaft, beklemmend" },
  { w:"おおう (覆う)", de:"bedecken, verhüllen" },
  { w:"つばさ (翼)", de:"Flügel" }
];
